# Generated by Django 3.0.7 on 2020-06-30 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('domain_or_ip', models.TextField(validators=[django.core.validators.RegexValidator(message='Incorrect domain or ip format', regex='^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?|^((http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$')])),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Request')),
            ],
            options={
                'db_table': 'blocked_domains',
            },
        ),
    ]
